export const GET_ALL_INCOMES = 'GET_ALL_INCOMES';
export const ADD_INCOME = 'ADD_INCOME';
export const UPDATE_INCOME = 'UPDATE_INCOME';
export const REMOVE_INCOME = 'REMOVE_INCOME';
export const CLEAR_INCOMES = 'CLEAR_INCOMES';
