export const GET_ALL_PLANNING = 'GET_ALL_PLANNING';
export const ADD_PLANNING = 'ADD_PLANNING';
export const UPDATE_PLANNING = 'UPDATE_PLANNING';
export const REMOVE_PLANNING = 'REMOVE_PLANNING';
export const CLEAR_PLANNING = 'CLEAR_PLANNING';
